name: ci/cd
on:
  push:
    branches: [main]
    paths:
      - "app"
      - "db"
      - "serverless"
      - "test"
      - "package.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install
        run: npm install

      - name: Unit test
        run: npm run test:unit

      - name: Api test
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]" >> ~/.aws/credentials
          echo "AWSAccessKeyId=xxxxxxxxxxxxxxxxxxxx" >> ~/.aws/credentials
          echo "AWSSecretKey=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >> ~/.aws/credentials
          echo "aws_access_key_id = xxxxxxxxxxxxxxxxxxxx" >> ~/.aws/credentials
          echo "aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >> ~/.aws/credentials
          npm run test:api
