name: github pages
on:
  push:
    branches: [main]
    paths:
      - "docs"
      - ".github/workflows/pages.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install
        run: |
          cd docs
          python -m pip install -r requirements.txt

      - name: Build and commit
        run: |
          git checkout pages
          git rebase
          cd docs
          sphinx-build -b html docs/source/ docs/build/html
          git add docs/build/html
          git commit -m "build html"
          git push